Algoritmo "niro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/08/2021
Var
   NOME,Idade:Caractere


Inicio

      Idade <- "20 anos"
      Escreva("qual o seu nome: ")
      Leia(NOME)
      Escreva("O meu nome e ", NOME, " tenho ", Idade)


Fimalgoritmo